//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginDetails.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Admin
    {
        public int Id { get; set; }
        [DisplayName("User ID")]
        [StringLength(20, MinimumLength = 4)]

        [Required(ErrorMessage = "User Id is a required field")]
        public string userid { get; set; }
        [DisplayName("Password")]
        [Required(ErrorMessage = "Password is a required field")]
        [StringLength(20, MinimumLength = 6)]
        [DataType(DataType.Password)]
        [RegularExpression("^(?=.*[A-Za-z])(?=.*\\d)[A-Za-z\\d^a-zA-Z0-9].{5,50}$", ErrorMessage = "Password Format is Worng")]
        public string password { get; set; }
        [DisplayName("Confirm Password")]
        [Required(ErrorMessage = "Confirm Password is a required field")]
        [DataType(DataType.Password)]
        [Compare("password", ErrorMessage = "Password is not identical")]
        public string confirm_password { get; set; }
    }
}
