//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginDetails.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Beneficiary
    {
        public int Id { get; set; }
        [DisplayName("First Name")]
        [StringLength(50, MinimumLength = 4)]

        [Required(ErrorMessage = "First Name is a required field")]
        public string firstname { get; set; }
        [DisplayName("Last Name")]
        [StringLength(50, MinimumLength = 4)]
        [Required(ErrorMessage = "Last Name is a required field")]
        public string lastname { get; set; }
        [Required(ErrorMessage = "Account Number is a required field")]
        [DisplayName("Account Number")]
        
        [RegularExpression(@"^[0-9]{14}$",ErrorMessage ="Account Number should be 14 character")]
        public long accountnumber { get; set; }
        [DisplayName("Bank Name")]
        [StringLength(50)]
        [Required(ErrorMessage = "Bank Name is a required field")]
        public string bankname { get; set; }
        [DisplayName("Branch Name")]
        [StringLength(50)]
        [Required(ErrorMessage = "Branch Name is a required field")]
        public string branchname { get; set; }
        [DisplayName("IFSC Code")]
        [StringLength(50)]
        [Required(ErrorMessage = "IFSC Code is a required field")]
        public string ifsccode { get; set; }
    }
}
