//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginDetails.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        public int Id { get; set; }
        [DisplayName("First Name")]
        [StringLength(50, MinimumLength = 4)]

        [Required(ErrorMessage = "First Name is a required field")]
        public string FirstName { get; set; }
        [DisplayName("Last Name")]
        [StringLength(50, MinimumLength = 4)]
        [Required(ErrorMessage = "Last Name is a required field")]
        public string LastName { get; set; }
        [DisplayName("Gender")]
        [Required(ErrorMessage = "Gender is a required field")]
        public string Gender { get; set; }
        [DisplayName("Age")]
        [Required(ErrorMessage = "Age is a required field")]
        [Range(18, 100, ErrorMessage = "Age must be between 18-100 in years.")]
        public int Age { get; set; }

        [DisplayName("Email")]
        [Required(ErrorMessage = "Email is a required field")]
        [RegularExpression("^([0-9a-zA-Z]([-\\.\\w]*[0-9a-zA-Z])*@([0-9a-zA-Z][-\\w]*[0-9a-zA-Z]\\.)+[a-zA-Z]{2,9})$", ErrorMessage = "Invalid Email Format")]
        public string Email { get; set; }
        [DisplayName("Contact Number")]
        [RegularExpression("^[7-9][0-9]{9}$", ErrorMessage = "Please enter valid phone no.")]
        [Required(ErrorMessage = "Mobile no. is required")]
        public long ContactNumber { get; set; }
        [DisplayName("Username")]
        [Required(ErrorMessage = "Username is a required field")]
        public string UserName { get; set; }
        [DisplayName("Password")]
        [Required(ErrorMessage = "Password is a required field")]
        [StringLength(20, MinimumLength = 6)]
        [DataType(DataType.Password)]
        [RegularExpression("^(?=.*[A-Za-z])(?=.*\\d)[A-Za-z\\d^a-zA-Z0-9].{5,50}$", ErrorMessage = "Password Format is Worng")]

        public string Password { get; set; }
        [DisplayName("Confirm Password")]
        [Required(ErrorMessage = "Confirm Password is a required field")]
        [DataType(DataType.Password)]
        [Compare("Password", ErrorMessage = "Password is not identical")]
        public string confirm_password { get; set; }

        [Required(ErrorMessage = "Account type is required field")]
        [DisplayName("Account Type")]
        public string AccountType { get; set; }
        public Nullable<decimal> AccountNumber { get; set; }
    }
}
